[build]
builder = "NIXPACKS"
buildCommand = "dotnet publish -c Release -o ./publish"

[build.environment]
DOTNET_VERSION =  "8.0.100-preview.5.23303.2"
ASPNETCORE_VERSION = "8.0"

[deploy]
numReplicas = 1
startCommand = "dotnet ./publish/WebApi-otica.dll"
restartPolicyType = "ON_FAILURE"