// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApi_otica.Data;

#nullable disable

namespace WebApi_otica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250604230221_slugAdd")]
    partial class slugAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImagensProdModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VariacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VariacaoId");

                    b.ToTable("ImagensProdutos");
                });

            modelBuilder.Entity("WebApi_otica.Model.ColecoesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescColecao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagemColecao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colecoes");
                });

            modelBuilder.Entity("WebApi_otica.Model.Produto.ProdutosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColecaoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColecaoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("WebApi_otica.Model.Produto.VariacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("VariacaoProdutos");
                });

            modelBuilder.Entity("ImagensProdModel", b =>
                {
                    b.HasOne("WebApi_otica.Model.Produto.VariacaoModel", "Variacao")
                        .WithMany("Imagens")
                        .HasForeignKey("VariacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variacao");
                });

            modelBuilder.Entity("WebApi_otica.Model.Produto.ProdutosModel", b =>
                {
                    b.HasOne("WebApi_otica.Model.ColecoesModel", "Colecao")
                        .WithMany("Produtos")
                        .HasForeignKey("ColecaoId");

                    b.Navigation("Colecao");
                });

            modelBuilder.Entity("WebApi_otica.Model.Produto.VariacaoModel", b =>
                {
                    b.HasOne("WebApi_otica.Model.Produto.ProdutosModel", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("WebApi_otica.Model.ColecoesModel", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("WebApi_otica.Model.Produto.ProdutosModel", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("WebApi_otica.Model.Produto.VariacaoModel", b =>
                {
                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
